name: Deploy Database Migrations

on:
  push:
    branches: [main, master]
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/deploy-migrations.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy migrations to production
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          # Link to production project
          supabase link --project-ref $SUPABASE_PROJECT_ID

          # Push migrations
          supabase db push --password $SUPABASE_DB_PASSWORD

          # Run seed file if it exists
          if [ -f "supabase/seed.sql" ]; then
            supabase db push --password $SUPABASE_DB_PASSWORD --include-seed
          fi

      - name: Verify deployment
        run: |
          echo "✅ Migrations deployed successfully"
          echo "Check your Supabase dashboard for confirmation"